### ISSUE TITLE
No output generated in "output" folder.

### ISSUE THREAD

**Issue by AsyncXeNo** [SwayamInSync/clothes-virtual-try-on#19] opened 2023-10-06 09:55 UTC
Hi, after following all the steps in the setup PDF, when I finally upload the files, no output it generated in the "output" folder, and the application throws an error.

**Comment by MosaabRkia** [comment] 2023-10-06 11:17
any solution for this issue ?

**Comment by M-AWAIS786** [comment] 2023-10-11 12:53
> any solution for this issue ?

you find solution?

**Comment by M-AWAIS786** [comment] 2023-10-11 12:54
> Hi, after following all the steps in the setup PDF, when I finally upload the files, no output it generated in the "output" folder, and the application throws an error.

i upload images when submit its show error index out of range any solution can write it here.

**Comment by punithan328** [comment] 2023-12-17 13:51
SAME PROBLEM CAN ANYONE HELP ME TO SOLVE THIS ERROR

**Comment by punithan328** [comment] 2023-12-17 13:52
> > Hi, after following all the steps in the setup PDF, when I finally upload the files, no output it generated in the "output" folder, and the application throws an error.
> 
> i upload images when submit its show error index out of range any solution can write it here.


SAME PROBLEM CAN ANYONE HELP ME TO SOLVE THIS ERROR

**Comment by SwayamInSync** [comment] 2023-12-17 13:56
Hey everyone, the problem is the Openpose installation (which is a crucial dependency for this project), the maintainer made some major code changes in their codebase leading to have a different installation method.

Currently I'm occupied with some personal work and college, will fix the code whenever I'll be free.

Till then please if you manage to fix it by yourself do post or make a PR

Thanks,
Swayam

**Comment by SwayamInSync** [comment] 2023-12-17 14:33
<img width="484" alt="Screenshot 2023-12-17 at 8 02 08 PM" src="https://github.com/SwayamInSync/clothes-virtual-try-on/assets/74960567/83cc831a-76e1-4957-b97d-4acc5f4ec5fd">

As per the recent update, their build is failing on all systems, will see if able to find any alternative (screenshot is from official [openpose](https://github.com/CMU-Perceptual-Computing-Lab/openpose) repo)

**Comment by SwayamInSync** [comment] 2023-12-18 05:24
As a solution
- Manually adding the openpose models to their respective directories and building it again using cuDNN seems to work
- Openpose eating way too much VRAM as not expected (with cuDNN), hence using the CPU only
- A little decrease in the performance (since it will not utilize the GPU)

Updating the codebase with working solution within 24 hours, (currently, my quota is exhausted so it'll take 24 hours at least)

PS: I'm also trying to get it work with cuDNN, it'll not compromise the performance (but for now without that works)

**Comment by SwayamInSync** [comment] 2023-12-19 15:59
> Hey everyone, the problem is the Openpose installation (which is a crucial dependency for this project), the maintainer made some major code changes in their codebase leading to have a different installation method.
> 
> Currently I'm occupied with some personal work and college, will fix the code whenever I'll be free.
> 
> Till then please if you manage to fix it by yourself do post or make a PR
> 
> Thanks, Swayam

So my exams are over and with that the mentioned issue is resolved and the setup is reduced to only 2 steps with the latest commit.

Thanks and closing this issue here, please open a new one if you found any problem with the current version

**Closed by SwayamInSync** 2023-12-19 15:59 UTC
Labels: dependency-issue

**Comment by punithan328** [comment] 2024-03-06 07:32
I am writing to express my heartfelt gratitude and appreciation for
VITON-HD. Your expertise, diligence, and responsiveness have been
invaluable. I extend the deepest thanks. You helped me alot, Cleared my
errors and responded quickly. Thank you once again.🙌
And just one more thing, Is there any other way to run this instead of
Google Collab.
